# -*- mode: ruby -*-
# vi: set ft=ruby :

# VARIABLES

BOX_IMAGE = "debian/bookworm64"
PROVIDER = "virtualbox"
NUM_CPUS = 2
MEMORIA_RAM = 2048
NOM_MAQUINA = "pj9f4a87-grup04" # Cambia XX por tu número de grupo
HOSTNAME = "pj9f4a87-grup04.fjeclot.net" # Cambia XX por tu número de grupo

# Rutas de carpetas compartidas según la estructura
CARPETA_MAQ_FIS1 = "../aplicacio1"
CARPETA_MAQ_VIR1 = "/home/vagrant/aplicacio1"
CARPETA_MAQ_FIS2 = "../aplicacio2"
CARPETA_MAQ_VIR2 = "/home/vagrant/aplicacio2"

# CONFIGURACIÓN DE LA MÁQUINA

Vagrant.configure("2") do |config|
  # BOX
  config.vm.box = BOX_IMAGE

  # CONFIGURACIÓN ESPECÍFICA DEL PROVIDER
  config.vm.provider PROVIDER do |provider|
    provider.name = NOM_MAQUINA
    provider.memory = MEMORIA_RAM
    provider.cpus = NUM_CPUS
    provider.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  # CONFIGURACIÓN GENERAL
  config.vm.hostname = HOSTNAME
  
  # Sincronización de carpetas según la estructura
  config.vm.synced_folder CARPETA_MAQ_FIS1, CARPETA_MAQ_VIR1
  config.vm.synced_folder CARPETA_MAQ_FIS2, CARPETA_MAQ_VIR2

  config.vm.network "public_network" # Eliminamos los puertos exportados

  # PROGRAMARI A INSTAL·LAR I ORDRES A EXECUTAR DURANTE LA CREACIÓN DE LA MÁQUINA (PROVISION)
  config.vm.provision "shell", inline: <<-SHELL
    #
    # Actualización de la lista de software. Instalación de software general
    #
    sudo apt-get -y update
    sudo apt-get -y install net-tools whois aptitude git zip unzip
    #
    # Instalación de Docker. Permiso al usuario vagrant para usar Docker
    #
    sudo apt-get -y install apt-transport-https ca-certificates curl gnupg2 software-properties-common
    curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    sudo apt-get update -y
    sudo apt-get -y install docker-ce docker-ce-cli containerd.io docker-compose
    sudo chown -R vagrant:vagrant /home/vagrant/
    sudo gpasswd -a vagrant docker
  SHELL
end
